Use malfix txid for outpoint
chaintope/rust-tapyruscore-rpc pull request #2
Opened 2024-07-08 07:46 UTC by rantan

This PR is depend on https://github.com/chaintope/rust-tapyrus/pulls

2024-07-12 04:30 UTC, Yamaguchi requested changes

2024-07-12 04:30 UTC, Yamaguchi commented on client/examples/test_against_node.rs
> +        rpc.get_by_id(&tapyrus_block.txdata[0].malfix_txid().to_raw_hash())?;
ここを変更するのではなく、get_by_idの引数の型の定義の方を変更すべきではないでしょうか

https://github.com/chaintope/rust-tapyruscore-rpc/blob/6d75022ce622c59bc83dd74d86cf1c505112691d/client/src/queryable.rs#L38

2024-07-12 05:56 UTC, rantan commented on client/examples/test_against_node.rs
> +        rpc.get_by_id(&tapyrus_block.txdata[0].malfix_txid().to_raw_hash())?;
変更します。

2024-07-16 05:20 UTC, Yamaguchi approved these changes

2024-07-18 06:53 UTC, merged